python3 main.py --method dp-sgd \
  --use_public 1 \
  --public_bs 20 \
  --epochs 32 \
  --scale 0 \
  --multiplier_cap 10000 \
  --division 100 \
  --coordinate_cap 1 \
  --momentum 0 \
  --momentum_parameter 0.9 \
  --sigma 1 \
  --batch_size 64 \
  --num_microbatches 16 \
  --scale_by freq \
  --scale_type 1 \
  --clipping_bound 2 \
  --seed 0 \
  --lr 1